addSbtPlugin("com.eed3si9n"       % "sbt-assembly"  % "2.1.1")
addSbtPlugin("org.scoverage"      % "sbt-scoverage" % "2.1.0")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"  % "2.5.0")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"       % "0.4.7")
addSbtPlugin("org.typelevel"      % "sbt-tpolecat"  % "0.5.2")
addSbtPlugin("org.jmotor.sbt" % "sbt-dependency-updates" % "1.2.9")
